const cards=window.SECRET_MATCH_CARDS||[];
let deck=[...cards],index=0,answers=JSON.parse(localStorage.getItem('secretMatchAnswers')||'{}'),history=[],sx=0,sy=0,dx=0,dy=0;
const screens={home:document.getElementById('screen-home'),game:document.getElementById('screen-game'),results:document.getElementById('screen-results')};
function shuffle(){deck=[...cards].sort(()=>Math.random()-.5);index=0;history=[];}
function show(n){Object.values(screens).forEach(s=>s.classList.remove('active'));screens[n].classList.add('active');document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',b.dataset.screen===n));if(n==='game')renderCard();if(n==='results')renderResults();}
function renderCard(){const st=document.getElementById('cardStage');if(index>=deck.length){show('results');return;}const c=deck[index];document.getElementById('progressText').textContent=(index+1)+' / '+deck.length;document.getElementById('progressFill').style.width=Math.round((index/deck.length)*100)+'%';st.innerHTML='<article id="activeCard" class="play-card"><div><div class="ill">'+c.icon+'</div><div class="meta">'+c.cat+'</div><h2 class="card-title">'+c.title+'</h2><p class="desc">'+c.desc+'</p><div class="tags">'+c.tags.map(t=>'<span class="tag">'+t+'</span>').join('')+'</div><p class="meta">ימינה רוצה · שמאלה לא · למעלה אולי</p></div><div class="choices"><button class="choice choose-yes" onclick="answer(\''+c.id+'\',\'yes\')">רוצה</button><button class="choice choose-maybe" onclick="answer(\''+c.id+'\',\'maybe\')">אולי</button><button class="choice choose-stop" onclick="answer(\''+c.id+'\',\'skip\')">לא</button></div><div class="choices"><button class="choice" onclick="goBack()">חזור</button><button class="choice" onclick="answer(\''+c.id+'\',\'skip\')">דלג</button></div></article>';swipe(c.id);}
function swipe(id){const el=document.getElementById('activeCard');el.ontouchstart=e=>{sx=e.touches[0].clientX;sy=e.touches[0].clientY;};el.ontouchmove=e=>{dx=e.touches[0].clientX-sx;dy=e.touches[0].clientY-sy;el.style.transform='translate('+dx+'px,'+dy+'px) rotate('+(dx/20)+'deg)';};el.ontouchend=()=>{if(dx>80)return answer(id,'yes');if(dx<-80)return answer(id,'skip');if(dy<-80)return answer(id,'maybe');dx=dy=0;el.style.transform='';};}
function answer(id,val){history.push({id,val,index});answers[id]=val;localStorage.setItem('secretMatchAnswers',JSON.stringify(answers));index++;renderCard();}
function goBack(){const last=history.pop();if(!last)return;delete answers[last.id];localStorage.setItem('secretMatchAnswers',JSON.stringify(answers));index=Math.max(0,last.index);renderCard();}
function score(v){return v==='yes'?100:v==='maybe'?50:0;}
function renderResults(){const list=document.getElementById('resultsList');const rows=cards.map(c=>({...c,score:score(answers[c.id])})).filter(c=>c.score>0).sort((a,b)=>b.score-a.score);document.getElementById('matchSummary').textContent=rows.length+' התאמות';list.innerHTML=rows.length?rows.map(x=>'<div class="result-item"><div><strong>'+x.icon+' '+x.title+'</strong><br><span class="meta">'+x.cat+'</span></div><div class="score">'+x.score+'%</div></div>').join(''):'<div class="empty">אין עדיין התאמות.</div>';}
document.getElementById('startBtn').onclick=()=>{shuffle();show('game')};document.getElementById('resetBtn').onclick=()=>{answers={};localStorage.removeItem('secretMatchAnswers');shuffle();show('home')};document.getElementById('backBtn').onclick=()=>show('home');document.getElementById('againBtn').onclick=()=>{shuffle();show('game')};document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>show(b.dataset.screen));
